#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 SERVER	the rsyslog server
#  $3 CLIENT	the rsyslog client
#  $4 ACTION    up or down
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=rsyslog/client

# arguments:
NODECTL=${1:-ws ssh}
SERVER=${2:-ws}
CLIENT=${3:-ws}
ACTION=${4:-up}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo SERVER: ${SERVER}
echo CLIENT: ${CLIENT}
echo ACTION: ${ACTION}
echo

UFWCOMMENT="${MODULENAME}-${CLIENT}"

case $1 in
	"up")
		# client side
		cat << EOF | ${NODECTL} ${CLIENT} "sudo tee /etc/rsyslog.d/client.conf"
*.* @${SERVER}
EOF
		${NODECTL} ${CLIENT} "
			sudo systemctl restart syslog
			"

		# server side
		${NODECTL} ${SERVER} "
			sudo ufw allow from ${CLIENT} to any proto udp port 514 comment ${UFWCOMMENT}
			"
		;;
	"down")
		# client side
		${NODECTL} ${CLIENT} "
			sudo rm -f /etc/rsyslog.d/client.conf
			sudo systemctl restart syslog
			"

		# server side
		RULENUM=$(./zss0 exec ${SERVER} "sudo ufw status numbered | grep ${UFWCOMMENT} | head -1 | cut -d] -f1 | cut -d[ -f2")
		while [ "${RULENUM}" != "" ]
		do
			echo y | ./zss0 exec ${SERVER} "sudo ufw delete ${RULENUM}"
			RULENUM=$(./zss0 exec ${SERVER} "sudo ufw status numbered | grep ${UFWCOMMENT} | head -1 | cut -d] -f1 | cut -d[ -f2")
		done
		;;
esac

