#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODEADM	the path of node-adm
#  $2 COLLECTOR	metrics collector
#  $3 ACTION    up or down
VERSION=0.1.1

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=monitoring/collector

# arguments:
NODEADM=${1:-../node-adm}
COLLECTOR=${2:ws}
ACTION=${3:-}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODEADM: ${NODEADM}
echo COLLECTOR: ${COLLECTOR}
echo ACTION: ${ACTION}
echo

cd ${NODEADM}
case ${ACTION} in
	"up")
		;;
	"down")
		;;
esac
cd - >& /dev/null

