#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODEADM	the path of node-adm
#  $2 NODE	the node to monitor
#  $3 COLLECTOR	metrics collector
#  $4 TGBOTTOKEN	the tg secret
#  $5 TGCHATID	the tg secret
#  $6 ACTION    up or down
VERSION=0.1.2

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=monitoring/node

# arguments:
NODEADM=${1:-../node-adm}
NODE=${2:ws}
COLLECTOR=${3:ws}
TGBOTTOKEN=${4:-}
TGCHATID=${5:-}
ACTION=${6:-}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODEADM: ${NODEADM}
echo NODE: ${NODE}
echo COLLECTOR: ${COLLECTOR}
echo TGBOTTOKEN: ${TGBOTTOKEN}
echo TGCHATID: ${TGCHATID}
echo ACTION: ${ACTION}
echo

cd ${NODEADM}
case ${ACTION} in
	"up")
		# for each node, bring up netdata
		./zss0 exec ${NODE} "
			cd ~/docker-apps/monitoring/netdata ;
			TGBOTTOKEN=${TGBOTTOKEN} TGCHATID=${TGCHATID} ./ws up ;
			"
		# wait for netdata /etc/netdata/health_alarm_notify.conf ready
		while ! ./zss0 exec ${NODE} "docker exec netdata su -s /bin/bash root -c 'chgrp netdata /etc/netdata/health_alarm_notify.conf' ;"
		do
			sleep 1
		done
		# issued a test notify
		./zss0 exec ${NODE} "
			docker exec netdata su -s /bin/bash netdata -c '/usr/libexec/netdata/plugins.d/alarm-notify.sh test' ;
			"

		./zss0 exec ${NODE} "
			sudo ufw allow in from $(dig +short ${COLLECTOR}) to any port 19999 comment 'monitoring-netdata' ;
			"
		;;
	"down")
		# uninstall NODE
		RULENUM=$(./zss0 exec ${NODE} "sudo ufw status numbered" | grep 'monitoring-netdata' | cut -d']' -f1 | cut -d'[' -f2)
		./zss0 exec ${NODE} "
			[ ! -z "${RULENUM}" ] && echo y | sudo ufw delete ${RULENUM} ;
			cd ~/docker-apps/monitoring/netdata ;
			TGBOTTOKEN=${TGBOTTOKEN} TGCHATID=${TGCHATID} ./ws down ;
			"
		;;
esac
cd - >& /dev/null

